"""
Dockerfile generator.

Takes a detection result from ``detect.detect_framework()`` and generates a
production-ready multi-stage Dockerfile.
"""

import os


def build_lock_copy_line(build_context: str) -> str:
    """
    Build a ``COPY`` line that includes all lock files present in the project.

    Checks for ``pnpm-lock.yaml``, ``yarn.lock``, and ``package-lock.json``
    in addition to the standard ``package*.json`` glob.
    """
    lock_copy = "COPY package*.json"
    if build_context:
        if os.path.exists(os.path.join(build_context, "pnpm-lock.yaml")):
            lock_copy += " pnpm-lock.yaml"
        if os.path.exists(os.path.join(build_context, "yarn.lock")):
            lock_copy += " yarn.lock"
        if os.path.exists(os.path.join(build_context, "package-lock.json")):
            lock_copy += " package-lock.json"
    lock_copy += " ./"
    return lock_copy


def generate_dockerfile(detection: dict, build_context: str = "") -> str:
    """
    Generate a production-ready Dockerfile based on the *detection* result.

    Parameters
    ----------
    detection : dict
        Output from :func:`detect.detect_framework`.
    build_context : str, optional
        Path to the project directory (used to check which lock files exist).
        If empty, only ``package*.json`` will be copied.

    Returns
    -------
    str
        The full Dockerfile contents, ready to be written to ``Dockerfile``.
    """
    fw = detection["framework"]
    lang = detection["language"]
    fw_type = detection["type"]
    build_cmd = detection.get("build_command")
    install_cmd = detection.get("install_command", "")
    start_cmd = detection.get("start_command", "")
    out_dir = detection.get("output_dir")
    port = detection.get("port", 3000)

    lock_copy = build_lock_copy_line(build_context)

    # Node.js static site (multi-stage: builder + caddy)
    if fw_type in ("node-static",) and build_cmd:
        return f"""# Auto-generated by pineapple — {fw} static site
FROM node:20-alpine AS builder
WORKDIR /app
{lock_copy}
RUN {install_cmd}
COPY . .
RUN {build_cmd}

FROM caddy:alpine
COPY --from=builder /app/{out_dir} /usr/share/caddy
EXPOSE {port}
CMD ["caddy", "file-server", "--root", "/usr/share/caddy", "--listen", ":{port}"]
"""

    # Node.js SSR app (multi-stage: builder + runner)
    if fw_type == "node-ssr":
        return f"""# Auto-generated by pineapple — {fw} SSR app
FROM node:20-alpine AS builder
WORKDIR /app
{lock_copy}
RUN {install_cmd}
COPY . .
RUN {build_cmd}

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/{out_dir} ./{out_dir}
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
EXPOSE {port}
CMD ["sh", "-c", "{start_cmd}"]
"""

    # Node.js server (single stage)
    if fw_type == "node-server" and lang == "node":
        return f"""# Auto-generated by pineapple — Node.js server
FROM node:20-alpine AS builder
WORKDIR /app
{lock_copy}
RUN {install_cmd}
COPY . .
{"RUN " + build_cmd if build_cmd else ""}

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app ./
EXPOSE {port}
CMD ["sh", "-c", "{start_cmd or 'node index.js'}"]
"""

    # Python
    if lang == "python":
        return f"""# Auto-generated by pineapple — Python {fw} app
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE {port}
CMD ["sh", "-c", "{start_cmd or 'python main.py'}"]
"""

    # Go
    if lang == "go":
        return f"""# Auto-generated by pineapple — Go app
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/server .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/server .
EXPOSE {port}
CMD ["./server"]
"""

    # Ruby
    if lang == "ruby":
        return f"""# Auto-generated by pineapple — Ruby {fw} app
FROM ruby:3.2-slim
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .
EXPOSE {port}
CMD ["sh", "-c", "{start_cmd or 'ruby app.rb'}"]
"""

    # PHP
    if lang == "php":
        return f"""# Auto-generated by pineapple — PHP {fw} app
FROM php:8.2-apache
WORKDIR /var/www/html
COPY composer.json ./
RUN composer install --no-dev --no-interaction
COPY . .
EXPOSE {port}
CMD ["sh", "-c", "{start_cmd or 'php -S 0.0.0.0:8080 -t public'}"]
"""

    # Rust
    if lang == "rust":
        return f"""# Auto-generated by pineapple — Rust app
FROM rust:1.77-slim AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {{}}" > src/main.rs
RUN cargo build --release 2>/dev/null || true
COPY . .
RUN cargo build --release
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/app .
EXPOSE {port}
CMD ["./app"]
"""

    # Fallback: Static HTML
    return f"""# Auto-generated by pineapple — Static HTML
FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
"""
