"""
.env file management for GitHub App credentials.
Stored at ~/.pineapple/.env
"""

import os
from pathlib import Path

ENV_DIR = Path.home() / ".pineapple"
ENV_PATH = ENV_DIR / ".env"

def _ensure_dir():
    ENV_DIR.mkdir(parents=True, exist_ok=True)

def _parse_env() -> dict:
    """Parse the .env file and return a dict."""
    if not ENV_PATH.exists():
        return {}
    result = {}
    with open(ENV_PATH) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, val = line.partition("=")
            result[key.strip()] = val.strip().strip("\"'")
    return result

def _write_env(data: dict) -> None:
    """Write a dict to .env file."""
    _ensure_dir()
    with open(ENV_PATH, "w") as f:
        f.write("# Pineapple GitHub App Configuration\n")
        f.write("# Generated by: pineapple github setup\n\n")
        for key, val in data.items():
            if val:
                f.write(f'{key}="{val}"\n')

def get_github_config() -> dict:
    """Get GitHub App credentials from .env."""
    env = _parse_env()
    return {
        "app_id": env.get("GITHUB_APP_ID", ""),
        "client_id": env.get("GITHUB_CLIENT_ID", ""),
        "client_secret": env.get("GITHUB_CLIENT_SECRET", ""),
        "private_key": env.get("GITHUB_PRIVATE_KEY", ""),
    }

def save_github_config(app_id: str, client_id: str, client_secret: str, private_key: str) -> None:
    """Save GitHub App credentials to .env."""
    env = _parse_env()
    env["GITHUB_APP_ID"] = app_id
    env["GITHUB_CLIENT_ID"] = client_id
    env["GITHUB_CLIENT_SECRET"] = client_secret
    env["GITHUB_PRIVATE_KEY"] = private_key
    _write_env(env)

def has_github_config() -> bool:
    """Check if GitHub App is configured."""
    cfg = get_github_config()
    return bool(cfg["app_id"] and cfg["client_id"] and cfg["client_secret"] and cfg["private_key"])
